### ISSUE TITLE
Error: could not load cache

### ISSUE THREAD

**Issue by Checiii** [rene-fonseca/base#4]
Hello, I have an error "Error: could not load cache" when i run command "cmake --build .. --config Debug --target install -- -j 4".
Could you help me to solve this error. Thank you very much!

**Comment by rene-fonseca** [comment]
Check that you have CMakeCache.txt in your build folder after the configuration step.

See:
[Build steps](https://github.com/rene-fonseca/base#release-build)

**Comment by Checiii** [comment]
Thanks,I got the right result.
^ ^
